const express = require("express");
const jobController = require("../controllers/jobController");
const auth = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/",auth, jobController.createJob);
router.get("/:id",auth, jobController.getJobById);
router.get("/",auth, jobController.getAllJobs);
router.patch("/:id",auth, jobController.updateJob);
router.delete("/:id",auth, jobController.deleteJob);
module.exports = router;